apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: guestbook-ui-static-auth
  namespace: app
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: guestbook-ui
    serviceAccount: guestbook-ui
    audiences:
      - vault